version: '3'

services:
  api:
    container_name: golang-api
    build: '.'
    environment:
      PORT: 8800
      REDIS_HOST: cache
      POSTGRES_HOST: db
      POSTGRES_DB: go_api
      POSTGRES_PASSWD: postgres
    depends_on:
      - db
      - cache 
    ports:
      - '8800:8800'
    restart: always   

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go_api  
    ports:
      - '5432:5432'
    volumes:
      - ./db/000001_create_db_initial.up.sql:/docker-entrypoint-initdb.d/000001_create_db_initial.up.sql
    restart: always

  cache:
    container_name: cache
    image: redis:latest    
    ports:
      - '6379:6379'
    restart: always