version: '3'

services:
  api:
    container_name: golang-api
    build: '.'
    environment:
      HOST_REDIS: redis
      FLASK_ENV: development
    depends_on:
      - redis  
    ports:
      - '8800:8800'
    restart: always   

  redis:
    container_name: redis
    image: redis:latest    
    ports:
      - '6379:6379'