version: '3'

services:
  api:
    container_name: golang-api
    build: '.'
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_DB: go_api
      POSTGRES_PASSWD: postgres
    depends_on:
      - db
      - redis 
    ports:
      - '8800:8800'
    restart: always   

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go_api  
    ports:
      - '5432:5432'
    restart: always

  redis:
    container_name: redis
    image: redis:latest    
    ports:
      - '6379:6379'
    restart: always